### ISSUE TITLE
Upload stops at 16%

### ISSUE THREAD

**Issue by komocode** [AFNetworking/AFAmazonS3Manager#21]
``` Objective-C
@interface NetworkManager : NSObject //singleton
{
    AFAmazonS3Client *_s3Client;
}
@end
- (id)init
{
    if( (self = [super init]) )
    {
        _s3Client = [[AFAmazonS3Client alloc] initWithAccessKeyID:ACCESS_KEY secret:ACCESS_SECRET];
        _s3Client.bucket = BUCKET_NAME;
    }
   return self
}
- (void)uploadDataWithFilePath:(NSString *)path videoName:(NSString *)videoName callback:(callbackBlock)callback
{
    [_s3Client postObjectWithFile:path destinationPath:@"/videos/" parameters:nil progress:^(NSUInteger bytesWritten, long long totalBytesWritten, long long totalBytesExpectedToWrite) {
        NSLog(@"%f%% Uploaded", (totalBytesWritten / (totalBytesExpectedToWrite * 1.0f) * 100));
    }  success:^(id responseObject) {
        callback(YES, nil);
    } failure:^(NSError *error) {
        NSLog(@"%@", error);
        callback(NO, @"There was a problem with uploading the video. Try uploading again.");

    }];

}
```

Output:

> 2013-07-15 18:29:33.160 divinenight[3814:907] 1.764420% Uploaded
> 2013-07-15 18:29:33.163 divinenight[3814:907] 3.528841% Uploaded
> 2013-07-15 18:29:33.165 divinenight[3814:907] 5.293261% Uploaded
> 2013-07-15 18:29:33.166 divinenight[3814:907] 7.049712% Uploaded
> 2013-07-15 18:29:33.227 divinenight[3814:907] 7.057681% Uploaded
> 2013-07-15 18:29:33.229 divinenight[3814:907] 7.232572% Uploaded
> 2013-07-15 18:29:33.247 divinenight[3814:907] 7.389802% Uploaded
> 2013-07-15 18:29:33.284 divinenight[3814:907] 7.547031% Uploaded
> 2013-07-15 18:29:33.298 divinenight[3814:907] 7.887122% Uploaded
> 2013-07-15 18:29:33.370 divinenight[3814:907] 8.437427% Uploaded
> 2013-07-15 18:29:33.379 divinenight[3814:907] 8.594656% Uploaded
> 2013-07-15 18:29:33.397 divinenight[3814:907] 8.751885% Uploaded
> 2013-07-15 18:29:33.408 divinenight[3814:907] 8.822101% Uploaded
> 2013-07-15 18:29:33.414 divinenight[3814:907] 8.987731% Uploaded
> 2013-07-15 18:29:33.432 divinenight[3814:907] 9.144960% Uploaded
> 2013-07-15 18:29:33.451 divinenight[3814:907] 9.380806% Uploaded
> 2013-07-15 18:29:33.479 divinenight[3814:907] 9.538035% Uploaded
> 2013-07-15 18:29:33.486 divinenight[3814:907] 9.695265% Uploaded
> 2013-07-15 18:29:33.526 divinenight[3814:907] 10.088340% Uploaded
> 2013-07-15 18:29:33.545 divinenight[3814:907] 10.245569% Uploaded
> 2013-07-15 18:29:33.563 divinenight[3814:907] 10.463753% Uploaded
> 2013-07-15 18:29:33.585 divinenight[3814:907] 10.586521% Uploaded
> 2013-07-15 18:29:33.596 divinenight[3814:907] 10.699597% Uploaded
> 2013-07-15 18:29:33.604 divinenight[3814:907] 10.856828% Uploaded
> 2013-07-15 18:29:33.638 divinenight[3814:907] 11.014057% Uploaded
> 2013-07-15 18:29:33.652 divinenight[3814:907] 11.171287% Uploaded
> 2013-07-15 18:29:33.661 divinenight[3814:907] 11.328517% Uploaded
> 2013-07-15 18:29:33.683 divinenight[3814:907] 11.564362% Uploaded
> 2013-07-15 18:29:33.702 divinenight[3814:907] 11.800206% Uploaded
> 2013-07-15 18:29:33.730 divinenight[3814:907] 11.957436% Uploaded
> 2013-07-15 18:29:33.737 divinenight[3814:907] 12.114666% Uploaded
> 2013-07-15 18:29:33.769 divinenight[3814:907] 12.350511% Uploaded
> 2013-07-15 18:29:33.780 divinenight[3814:907] 12.350942% Uploaded
> 2013-07-15 18:29:33.783 divinenight[3814:907] 12.507740% Uploaded
> 2013-07-15 18:29:33.814 divinenight[3814:907] 12.664970% Uploaded
> 2013-07-15 18:29:33.826 divinenight[3814:907] 12.822201% Uploaded
> 2013-07-15 18:29:33.835 divinenight[3814:907] 13.058044% Uploaded
> 2013-07-15 18:29:33.868 divinenight[3814:907] 13.293889% Uploaded
> 2013-07-15 18:29:33.877 divinenight[3814:907] 13.451118% Uploaded
> 2013-07-15 18:29:33.901 divinenight[3814:907] 13.608350% Uploaded
> 2013-07-15 18:29:33.937 divinenight[3814:907] 14.001423% Uploaded
> 2013-07-15 18:29:33.950 divinenight[3814:907] 14.115362% Uploaded
> 2013-07-15 18:29:33.965 divinenight[3814:907] 14.237268% Uploaded
> 2013-07-15 18:29:33.984 divinenight[3814:907] 14.473113% Uploaded
> 2013-07-15 18:29:34.000 divinenight[3814:907] 14.630343% Uploaded
> 2013-07-15 18:29:34.016 divinenight[3814:907] 14.787573% Uploaded
> 2013-07-15 18:29:34.033 divinenight[3814:907] 14.944802% Uploaded
> 2013-07-15 18:29:34.049 divinenight[3814:907] 15.102032% Uploaded
> 2013-07-15 18:29:34.064 divinenight[3814:907] 15.259263% Uploaded
> 2013-07-15 18:29:34.083 divinenight[3814:907] 15.416492% Uploaded
> 2013-07-15 18:29:34.097 divinenight[3814:907] 15.573722% Uploaded
> 2013-07-15 18:29:34.115 divinenight[3814:907] 15.730951% Uploaded
> 2013-07-15 18:29:34.132 divinenight[3814:907] 15.879782% Uploaded
> 2013-07-15 18:29:34.149 divinenight[3814:907] 16.045410% Uploaded
> 2013-07-15 18:29:34.168 divinenight[3814:907] 16.202641% Uploaded
> 2013-07-15 18:29:34.181 divinenight[3814:907] 16.438486% Uploaded
> 2013-07-15 18:29:34.217 divinenight[3814:907] 16.595715% Uploaded
> 2013-07-15 18:29:34.229 divinenight[3814:907] 16.752947% Uploaded
>  Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo=0x1d9c70e0 {NSErrorFailingURLStringKey=http://divinenight.s3.amazonaws.com/videos/, NSErrorFailingURLKey=http://divinenight.s3.amazonaws.com/videos/, NSLocalizedDescription=The request timed out., NSUnderlyingError=0x1d9c83e0 "The request timed out."}

Repeated the process, same outcome every time.

**Comment by holgersindbaek** [comment]
I'm having exact same error here. Anybody managed to find out how to fix it? Either through Amazons configuration or...?

**Comment by chrisballinger** [comment]
I've found Amazon's own SDK to be the most reliable, although their code is
full of Java/Enterprise coding patterns.

**Comment by elsurudo** [comment]
Also having this issue. Nobody has found a workaround yet?
