### ISSUE TITLE
uploading with public-read permissions

### ISSUE THREAD

**Issue by vinced45** [AFNetworking/AFAmazonS3Manager#44]
I'm trying to upload a file with public-read permissions but have been unsuccessful. Here is the call I'm trying to do to add the acl to the header:

<pre>
[s3Manager.requestSerializer setValue:@"public-read" forHTTPHeaderField:@"x-amz-acl"];
</pre>

**Comment by vijaytholpadi** [comment]
Thanks a ton! Came in quite handy.
