### ISSUE TITLE
Add meaningful response objects

### ISSUE THREAD

**Issue by abbeycode** [AFNetworking/AFAmazonS3Manager#70]
Amazon S3's HTTP responses have no payload, but the responses are treated as XML with the `AFXMLParserResponseSerializer`. Unfortunately, this buries the useful information included in the response: the URL of the resulting file, and the ETag (MD5 hash) of the file.

It would make sense to add a dedicated `AFAmazonS3ResponseSerializer`, the same way requests have a special handler. This should return a new class `AFAmazonS3ResponseObject`, which encapsulates the raw header info.

**Comment by mattt** [comment]
See #70.
