### ISSUE TITLE
Conflicting return type in implementation "headObjectWithPath:success:failure" warning.

### ISSUE THREAD

**Issue by jacobsologub** [AFNetworking/AFAmazonS3Manager#75]
Getting a:

<code>
Conflicting return type in implementation of 'headObjectWithPath:success:failure:': 'void' vs 'AFHTTPRequestOperation *'
</code>

Warning in:

<code>
AFAmazonS3Manager.m line #137
</code>

**Comment by mattt** [comment]
It looks like this was missed in #73. I've fixed this with 051d1ae19c43296383568c166236f422d52db162.
