### ISSUE TITLE
Uploading multiple images

### ISSUE THREAD

**Issue by holgersindbaek** [AFNetworking/AFAmazonS3Manager#77]
How would I go about that? It seems to me, it's only possible to upload one image at a time?

UPDATE:

I think I got ahead of myself before. I can't even upload a single image. Would it be possible to provide some dummy code displaying how to upload a single UIImage? And if possible, how to upload multiple UIImages?

**Comment by holgersindbaek** [comment]
No suggestions? I'm using this code to upload (Rubymotion):

    amazon_manager = AFAmazonS3Manager.alloc.initWithAccessKeyID("######", secret:"######")
    amazon_manager.requestSerializer.region = AFAmazonS3USWest2Region
    amazon_manager.requestSerializer.bucket = "#####"

    NSLog "right.jpg.temporary_path: #{"right.jpg".temporary_path}"

    amazon_manager.postObjectWithFile("right.jpg".temporary_path,
      destinationPath:"right.jpg",
      parameters:nil,
      progress: lambda { |bytesWritten, totalBytesWritten, totalBytesExpectedToWrite|
        NSLog "uploading #{totalBytesWritten} - #{totalBytesExpectedToWrite}"
        NSLog "Uploaded: #{(totalBytesWritten/(totalBytesExpectedToWrite*1))*100}"
      }, success: lambda { |responseObject|
        NSLog "upload complete: #{responseObject.URL}"
      }, failure:lambda { |error|
        NSLog "error: #{error}"
      })

Image is present and uploading, but then it ends up with an error. Logs: 

    Feb  6 11:25:36 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: right.jpg.temporary_path: /private/var/mobile/Containers/Data/Application/59567AE7-BEEA-4A45-87EB-E7BEF6C606C2/tmp/right.jpg
    Feb  6 11:25:36 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 32768 - 895871
    Feb  6 11:25:36 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 65536 - 895871
    Feb  6 11:25:36 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 98304 - 895871
    Feb  6 11:25:36 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 131072 - 895871
    Feb  6 11:25:36 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 163840 - 895871
    Feb  6 11:25:37 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 196608 - 895871
    Feb  6 11:25:37 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 229376 - 895871
    Feb  6 11:25:37 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 262144 - 895871
    Feb  6 11:25:37 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 294912 - 895871
    Feb  6 11:25:37 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 327680 - 895871
    Feb  6 11:25:37 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 360448 - 895871
    Feb  6 11:25:37 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 393216 - 895871
    Feb  6 11:25:37 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 425984 - 895871
    Feb  6 11:25:37 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 458752 - 895871
    Feb  6 11:25:37 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 491520 - 895871
    Feb  6 11:25:37 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 524288 - 895871
    Feb  6 11:25:37 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 557056 - 895871
    Feb  6 11:25:37 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 589824 - 895871
    Feb  6 11:25:37 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 655360 - 895871
    Feb  6 11:25:37 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 688128 - 895871
    Feb  6 11:25:37 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 720896 - 895871
    Feb  6 11:25:37 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 753664 - 895871
    Feb  6 11:25:37 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 786432 - 895871
    Feb  6 11:25:37 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 819200 - 895871
    Feb  6 11:25:37 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 851968 - 895871
    Feb  6 11:25:37 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 884736 - 895871
    Feb  6 11:25:37 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: uploading 895871 - 895871
    Feb  6 11:25:37 Holger-Sindbaeks-iPhone Slang[8065] <Warning>: error: #<NSError:0x57b1a20, description="Request failed: method not allowed (405)", code=-1011, domain="com.alamofire.error.serialization.response", userInfo={"com.alamofire.serialization.response.error.response"=>#<NSHTTPURLResponse:0x40f5320>, "NSErrorFailingURLKey"=>#<NSURL:0x456dfd0, URL="https://#####.s3-us-west-2.amazonaws.com/right.jpg">, "NSLocalizedDescription"=>"Request failed: method not allowed (405)", "com.alamofire.serialization.response.error.data"=><?xml version="1.0" encoding="UTF-8"?>

@mattt Any suggestions?

**Comment by mattt** [comment]
A 405 indicates that you do not have the necessary credentials to put objects to that bucket. `AFAmazonS3Manager` is working as expected.
