### ISSUE TITLE
Security concerns?

### ISSUE THREAD

**Issue by pandolin** [AFNetworking/AFAmazonS3Manager#81]
We're building an iOS app that needs to store content on S3. We've been using AFAmazonS3Manager for testing purposes for the past few months and have loved it. However, we were under the impression that it is very bad practice to include our access key and secret hard-coded into the client app. Is this meant to be baked into the final product, or a framework for getting apps up and running, intended to be the stepping stone before graduating to something like Amazon Cognito? 

Thanks!

**Comment by mattt** [comment]
This library makes no assumptions about where client credentials are stored or retrieved. Depending on your particular security requirements, credentials could be generated on a server and retrieved by an HTTPS request, for example, and pass those into initialized managers.
