### ISSUE TITLE
Complier Warning: "Auto property synthesis will not synthesize property"

### ISSUE THREAD

**Issue by greenski** [AFNetworking/AFAmazonS3Manager#85]
When using Xcode 6.3 Beta 3 AFAmazonS3Manager.h generates a compiler warning as follows: 
```
Auto property synthesis will not synthesize property 'requestSerializer'; it will be implemented by its superclass, use @dynamic to acknowledge intention
```
I've made a pull request #84 [b27c34d](https://github.com/greenski/AFAmazonS3Manager/commit/b27c34d318d239cef5e439ab5b45d56a96e0a02b "#84 b27c34d") that seems to take care of the issue by adding the specified @dynamic call in the @implementation, but someone should probably check to make sure that's the correct approach.

Thanks, 
daSkier

**Comment by mattt** [comment]
Fixed by #84. Thanks again, @greenski.
