### ISSUE TITLE
Can't upload

### ISSUE THREAD

**Issue by bagusflyer** [AFNetworking/AFAmazonS3Manager#87]
I got the following error message:

Error: Error Domain=NSURLErrorDomain Code=-1021 "request body stream exhausted"

The code to upload is the one in your readme file.

**Comment by mattt** [comment]
Asked and answered here: http://stackoverflow.com/questions/16068158/domain-nsurlerrordomain-code-1021-request-body-stream-exhausted

**Comment by fitch** [comment]
I started getting this error (`File upload failed with error: Error Domain=NSURLErrorDomain Code=-1012 "The operation couldn’t be completed. (NSURLErrorDomain error -1012.)"`) yesterday with all requests, tested with two iPhone 6 devices / iOS 8.3. Could this be some sort of an authorization problem from Amazon's side? Using the same API key + secret with `aws` command line works ok.

**Comment by fitch** [comment]
This seems to be related to AFNetworking 2.5.3, see my new issue here: https://github.com/AFNetworking/AFAmazonS3Manager/issues/90

**Comment by AndrewHartAR** [comment]
I'm having this latter issue. Did you manage to resolve it?
